### ISSUE TITLE
Which version of Pattern Lab are you recommending?

### ISSUE THREAD

**Issue by pdureau** [backlineint/ui_patterns_pattern_lab#10]
Hi,

To use with ui_patterns_pattern_lab module, are you using/recommending ?
* Standard Edition for Twig, alone https://github.com/pattern-lab/edition-php-twig-standard
* Standard Edition for Twig +  Data Transform Plugin https://github.com/aleksip/plugin-data-transform
* Standard Edition for Drupal https://github.com/pattern-lab/edition-php-drupal-standard which already includes Twig & Data Transform Plugin 

On the PL side, are they some tweaks/settings you recommend to make the integration easier or more powerful?

**Comment by backlineint** [comment]
@pdureau the module should work with either the Twig edition or the Drupal edition of Pattern Lab.  In general I'd recommend using the Standard Edition for Twig as that is what @evanlovely advised recently on the pattern-lab channel in the Drupaltwig slack.

At the moment, I don't think this module would be able to handle the syntax used by the data transform plugin.  It might be worth trying to build in some support for it for a couple of reasons though. It is useful and widely used. Also, as I've been testing this with Pattern Lab instances I think there is some room for improvement regarding how sub-patterns are handled.  I wonder if the transform plugins include syntax (or something inspired by it) could help. (cc @aleksip)

The main thing I'm working on at the moment is running this against a variety of Pattern Lab instances. As I try more, I'd imagine I'll also have more specific recommendations here.

@pdureau thanks again for your work on the Fractal version.  Hope this Pattern Lab adaptation proves useful.

**Comment by backlineint** [comment]
Closing this one. Recommending the Standard Edition for Twig, but the Drupal edition will work as well.   We should also test with the 3.0 version of Pattern Lab node as that seems to be the future of the project. Created #20 to track that.
