### ISSUE TITLE
Variant Support

### ISSUE THREAD

**Issue by backlineint** [backlineint/ui_patterns_pattern_lab#21]
The 1.x of this module should ideally have feature parity with UI Patterns 1.x so we should support the recently added variants functionality. This has also been requested on our d.o issue queue https://www.drupal.org/project/ui_patterns_pattern_lab/issues/3013455

**Comment by ipwa** [comment]
This issue will be worked on and tracked in d.o, please close. Thank you :)

**Comment by backlineint** [comment]
Closing as requested.
